### ISSUE TITLE
Create R-based notebook to explore taxonomy

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc_notebooks#32]
https://github.com/microbiomedata/notebook_hackathons/tree/main/taxonomic_dist_by_soil_layer
Only has a python example.  

We should add an R version to mirror the other notebooks.

**Comment by mslarae13** [comment]
Katherine is out this week & next. Not sure if she'll get to it July 8-12, but obviously not July 1-5

**Comment by ssarrafan** [comment]
I'll remove from sprint and add backlog label
@kheal please add to a future sprint when you're ready to work on this
